#!/usr/bin/env python
"""Adapter for IMO problem JSON of the lmms-lab/imo-<year> shape.

Source: https://huggingface.co/datasets/lmms-lab/imo-2025 (MIT license; problem text
sourced from https://www.imo-official.org). Input is a JSON list of rows:

    [{"id": "2025-imo-p1", "problem": "<markdown+LaTeX statement>", "solution": null}, ...]

The statements use `$$...$$` display math and markdown emphasis, which the frontend can't
render; base.normalize_statement() converts them to the KaTeX-safe inline-`$...$` form.
Solutions are intentionally dropped (link-out licensing policy; here they're null anyway).

    python scripts/adapters/imo_json.py path/to/imo_2025.json --out data
    python scripts/adapters/imo_json.py path/to/imo_2025.json --dry-run
"""

import argparse
import json
import re
import sys
from pathlib import Path

try:
    from .base import Adapter, CanonicalProblem, YearFile, normalize_statement
except ImportError:  # run directly as a script
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from base import Adapter, CanonicalProblem, YearFile, normalize_statement

_ID_RE = re.compile(r"(?P<year>\d{4})-imo-p(?P<num>\d+)", re.IGNORECASE)

COMPETITION = {
    "name": "IMO",
    "country": "International",
    "url": "https://www.imo-official.org",
}


class ImoJsonAdapter(Adapter):
    name = "imo_json"

    def parse(self, source: Path) -> list:
        rows = json.loads(Path(source).read_text(encoding="utf-8"))
        by_year: dict[int, list] = {}
        for row in rows:
            m = _ID_RE.match(str(row.get("id", "")))
            if not m:
                raise ValueError(f"{self.name}: unrecognized id {row.get('id')!r} "
                                 f"(expected '<year>-imo-p<n>')")
            year = int(m.group("year"))
            number = int(m.group("num"))
            statement = normalize_statement(row["problem"])
            by_year.setdefault(year, []).append(
                CanonicalProblem(
                    number=number,
                    statement=statement,
                    source_url=f"https://www.imo-official.org/year_info.aspx?year={year}",
                )
            )
        header = (
            "Generated by scripts/adapters/imo_json.py — do not edit by hand.\n"
            "Source: https://huggingface.co/datasets/lmms-lab/imo-2025 (MIT license);\n"
            "problem statements are published facts from https://www.imo-official.org.\n"
            "Markdown/display-math normalized to KaTeX-safe inline $...$."
        )
        return [
            YearFile(competition=dict(COMPETITION), year=year, problems=probs, header=header)
            for year, probs in sorted(by_year.items())
        ]


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("source", help="path to the imo_<year>.json file")
    parser.add_argument("--out", default="data", help="output data directory (default: data)")
    parser.add_argument("--dry-run", action="store_true", help="validate without writing")
    parser.add_argument("--no-katex", action="store_true", help="skip KaTeX validation")
    args = parser.parse_args()

    adapter = ImoJsonAdapter()
    paths = adapter.emit(
        Path(args.source),
        Path(args.out),
        check_katex=not args.no_katex,
        dry_run=args.dry_run,
    )
    prefix = "[dry-run] would write" if args.dry_run else "wrote"
    for p in paths:
        print(f"{prefix}: {p}")


if __name__ == "__main__":
    main()
