#!/usr/bin/env python
"""Adapter for a per-problem LaTeX tree of the ZeusDM/latex-problems shape.

Source layout (point --root at the `imo` directory of a local checkout of
https://github.com/ZeusDM/latex-problems, i.e. `problems/math/imo`):

    <root>/<year>/<number>/problem_en.tex     # English statement (LaTeX)

The .tex statements use text-mode LaTeX the frontend can't render (enumerate/itemize,
\\[...\\] display math, \\emph, % comments); base.normalize_latex() converts them to the
KaTeX-safe inline-$...$ form. Statements are published facts; source_url points at the
official IMO page. (The upstream repo has no LICENSE; only the statements — facts — are
reproduced, not the repo's packaging.)

    python scripts/adapters/imo_tex_tree.py /path/to/latex-problems/problems/math/imo --out data
    python scripts/adapters/imo_tex_tree.py <root> --years 2015-2020 --dry-run
"""

import argparse
import sys
from pathlib import Path

try:
    from .base import Adapter, CanonicalProblem, YearFile, normalize_latex
except ImportError:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from base import Adapter, CanonicalProblem, YearFile, normalize_latex

COMPETITION = {"name": "IMO", "country": "International", "url": "https://www.imo-official.org"}

HEADER = (
    "Generated by scripts/adapters/imo_tex_tree.py — do not edit by hand.\n"
    "Source: https://github.com/ZeusDM/latex-problems (problems/math/imo/<year>/<n>);\n"
    "problem statements are published facts from https://www.imo-official.org.\n"
    "LaTeX (enumerate/itemize, display math, emphasis) normalized to KaTeX-safe inline $...$."
)


def _parse_year_range(spec: str):
    if not spec:
        return None
    years = set()
    for part in spec.split(","):
        if "-" in part:
            a, b = part.split("-")
            years.update(range(int(a), int(b) + 1))
        else:
            years.add(int(part))
    return years


class ImoTexTreeAdapter(Adapter):
    name = "imo_tex_tree"

    def __init__(self, years=None):
        self.years = years

    def parse(self, source: Path) -> list:
        root = Path(source)
        by_year: dict[int, list] = {}
        for tex in sorted(root.glob("*/*/problem_en.tex")):
            year = int(tex.parent.parent.name)
            number = int(tex.parent.name)
            if self.years and year not in self.years:
                continue
            statement = normalize_latex(tex.read_text(encoding="utf-8"))
            by_year.setdefault(year, []).append(
                CanonicalProblem(
                    number=number,
                    statement=statement,
                    source_url=f"https://www.imo-official.org/year_info.aspx?year={year}",
                )
            )
        if not by_year:
            raise FileNotFoundError(f"no <year>/<n>/problem_en.tex found under {root}")
        return [
            YearFile(competition=dict(COMPETITION), year=year, problems=probs, header=HEADER)
            for year, probs in sorted(by_year.items())
        ]


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("root", help="path to the imo/ dir (problems/math/imo of the repo)")
    parser.add_argument("--out", default="data")
    parser.add_argument("--years", default=None, help="filter, e.g. '2015-2020' or '2015,2018'")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--no-katex", action="store_true")
    args = parser.parse_args()

    adapter = ImoTexTreeAdapter(years=_parse_year_range(args.years))
    paths = adapter.emit(Path(args.root), Path(args.out),
                         check_katex=not args.no_katex, dry_run=args.dry_run)
    prefix = "[dry-run] would write" if args.dry_run else "wrote"
    for p in paths:
        print(f"{prefix}: {p}")


if __name__ == "__main__":
    main()
