#!/usr/bin/env python
"""Adapter for the jonaskg/imo-problems-complete dataset (HuggingFace, MIT).

Source: https://huggingface.co/datasets/jonaskg/imo-problems-complete
A single JSONL file, one problem per line: {year, problem_number, problem, solution}.
Statements use Evan-Chen `evan.sty` macros (\\RR, \\ts, \\dg, \\dotsb, ...) which KaTeX
doesn't know; _expand_macros() rewrites them to standard LaTeX, then base.normalize_statement
converts to the KaTeX-safe inline-$...$ form.

    curl -sL "https://huggingface.co/datasets/jonaskg/imo-problems-complete/resolve/main/all_imo_problems.jsonl" -o imo.jsonl
    python scripts/adapters/imo_jonaskg.py imo.jsonl --years 2021-2023 --out data

Known upstream defect: 2023 Problem 1 drops the divisor-ordering clause. It is corrected
here from the cross-checked kylemontgomery/imo mirror of the official statement (see
KNOWN_FIXES); everything else is used verbatim from the MIT source.
"""

import argparse
import json
import re
import sys
from pathlib import Path

try:
    from .base import Adapter, CanonicalProblem, YearFile, normalize_latex
    from .imo_tex_tree import _parse_year_range
except ImportError:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from base import Adapter, CanonicalProblem, YearFile, normalize_latex
    from imo_tex_tree import _parse_year_range

COMPETITION = {"name": "IMO", "country": "International", "url": "https://www.imo-official.org"}

# evan.sty macros -> standard LaTeX (applied before normalization).
_BLACKBOARD = {"RR": "R", "ZZ": "Z", "NN": "N", "QQ": "Q", "CC": "C"}
_DOTS = {r"\dotsb": r"\cdots", r"\dotsm": r"\cdots", r"\dotsc": r"\ldots"}

# Corrections for verified upstream transcription defects. Source of the fix noted inline.
KNOWN_FIXES = {
    # jonaskg drops "1 = d_1 < ... < d_k = n"; restored from kylemontgomery/imo (AoPS mirror
    # of the official statement), cross-checked against imo-official.
    (2023, 1): (
        r"Determine all composite integers $n > 1$ that satisfy the following property: "
        r"if $d_1, d_2, \dots, d_k$ are all the positive divisors of $n$ with "
        r"$1 = d_1 < d_2 < \dots < d_k = n$, then $d_i$ divides $d_{i+1} + d_{i+2}$ "
        r"for every $1 \le i \le k - 2$."
    ),
}


def _expand_macros(text: str) -> str:
    for name, letter in _BLACKBOARD.items():
        text = re.sub(rf"\\{name}(?![A-Za-z])", rf"\\mathbb{{{letter}}}", text)
    for src, dst in _DOTS.items():
        text = text.replace(src, dst)
    text = re.sub(r"\\dg(?![A-Za-z])", r"^{\\circ}", text)   # degree
    text = re.sub(r"\\ts\{([^{}]*)\}", r"\1", text)          # \ts{th} -> th
    return text


class ImoJonaskgAdapter(Adapter):
    name = "imo_jonaskg"

    def __init__(self, years=None):
        self.years = years

    def parse(self, source: Path) -> list:
        rows = [json.loads(l) for l in Path(source).read_text(encoding="utf-8").splitlines() if l.strip()]
        by_year: dict[int, list] = {}
        for r in rows:
            year, number = int(r["year"]), int(r["problem_number"])
            if self.years and year not in self.years:
                continue
            raw = KNOWN_FIXES.get((year, number), r["problem"])
            statement = normalize_latex(_expand_macros(raw))
            by_year.setdefault(year, []).append(
                CanonicalProblem(
                    number=number,
                    statement=statement,
                    source_url=f"https://www.imo-official.org/year_info.aspx?year={year}",
                )
            )
        if not by_year:
            raise ValueError("no matching rows for the requested years")
        header = (
            "Generated by scripts/adapters/imo_jonaskg.py — do not edit by hand.\n"
            "Source: https://huggingface.co/datasets/jonaskg/imo-problems-complete (MIT);\n"
            "statements are published facts from https://www.imo-official.org.\n"
            "evan.sty macros expanded; math normalized to KaTeX-safe inline $...$."
        )
        return [
            YearFile(competition=dict(COMPETITION), year=year, problems=probs, header=header)
            for year, probs in sorted(by_year.items())
        ]


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("source", help="path to all_imo_problems.jsonl")
    parser.add_argument("--out", default="data")
    parser.add_argument("--years", default=None, help="filter, e.g. '2021-2023'")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--no-katex", action="store_true")
    args = parser.parse_args()

    adapter = ImoJonaskgAdapter(years=_parse_year_range(args.years))
    paths = adapter.emit(Path(args.source), Path(args.out),
                         check_katex=not args.no_katex, dry_run=args.dry_run)
    prefix = "[dry-run] would write" if args.dry_run else "wrote"
    for p in paths:
        print(f"{prefix}: {p}")


if __name__ == "__main__":
    main()
